version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db && configs:
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_USER=daker
      - DB_PASS=password
      - DB_NAME=recipe
      - DB_PORT=3306
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    volumes:
      - dev-db-data:/var/lib/mysql/
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=daker
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=recipe

volumes:
  dev-db-data:
